version: "3"
services:
  app:
    image: leitato/jpay
    container_name: jpay-exercise-dev
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "9000:9000"
      - "9090:9090"

